/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AttachmentsRouteImport } from './routes/attachments'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCirclesRouteImport } from './routes/_app/circles'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppTimeRouteImport } from './routes/_app/time'
import { Route as AppWeekRouteImport } from './routes/_app/week'
import { Route as AttachmentsIdRouteImport } from './routes/attachments.$id'
import { Route as DevSeedRouteImport } from './routes/dev/seed'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentsRoute = AttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekRoute = AppWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AppRoute,
} as any)
const AttachmentsIdRoute = AttachmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AttachmentsRoute,
} as any)
const DevSeedRoute = DevSeedRouteImport.update({
  id: '/dev/seed',
  path: '/dev/seed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/attachments': typeof AttachmentsRouteWithChildren
  '/live': typeof LiveRoute
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/circles': typeof AppCirclesRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRoute
  '/metrics': typeof AppMetricsRoute
  '/more': typeof AppMoreRoute
  '/projects': typeof AppProjectsRoute
  '/time': typeof AppTimeRoute
  '/week': typeof AppWeekRoute
  '/attachments/$id': typeof AttachmentsIdRoute
  '/dev/seed': typeof DevSeedRoute
}
export interface FileRoutesByTo {
  '/attachments': typeof AttachmentsRouteWithChildren
  '/live': typeof LiveRoute
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/circles': typeof AppCirclesRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRoute
  '/metrics': typeof AppMetricsRoute
  '/more': typeof AppMoreRoute
  '/projects': typeof AppProjectsRoute
  '/time': typeof AppTimeRoute
  '/week': typeof AppWeekRoute
  '/attachments/$id': typeof AttachmentsIdRoute
  '/dev/seed': typeof DevSeedRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/attachments': typeof AttachmentsRouteWithChildren
  '/live': typeof LiveRoute
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_app/circles': typeof AppCirclesRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/time': typeof AppTimeRoute
  '/_app/week': typeof AppWeekRoute
  '/attachments/$id': typeof AttachmentsIdRoute
  '/dev/seed': typeof DevSeedRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attachments'
    | '/live'
    | '/sign-in'
    | '/sso-callback'
    | '/circles'
    | '/integrations'
    | '/invoices'
    | '/metrics'
    | '/more'
    | '/projects'
    | '/time'
    | '/week'
    | '/attachments/$id'
    | '/dev/seed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/attachments'
    | '/live'
    | '/sign-in'
    | '/sso-callback'
    | '/circles'
    | '/integrations'
    | '/invoices'
    | '/metrics'
    | '/more'
    | '/projects'
    | '/time'
    | '/week'
    | '/attachments/$id'
    | '/dev/seed'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/attachments'
    | '/live'
    | '/sign-in'
    | '/sso-callback'
    | '/_app/circles'
    | '/_app/integrations'
    | '/_app/invoices'
    | '/_app/metrics'
    | '/_app/more'
    | '/_app/projects'
    | '/_app/time'
    | '/_app/week'
    | '/attachments/$id'
    | '/dev/seed'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AttachmentsRoute: typeof AttachmentsRouteWithChildren
  LiveRoute: typeof LiveRoute
  SignInRoute: typeof SignInRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  DevSeedRoute: typeof DevSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachments': {
      id: '/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles': {
      id: '/_app/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time': {
      id: '/_app/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week': {
      id: '/_app/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AppWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/attachments/$id': {
      id: '/attachments/$id'
      path: '/$id'
      fullPath: '/attachments/$id'
      preLoaderRoute: typeof AttachmentsIdRouteImport
      parentRoute: typeof AttachmentsRoute
    }
    '/dev/seed': {
      id: '/dev/seed'
      path: '/dev/seed'
      fullPath: '/dev/seed'
      preLoaderRoute: typeof DevSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCirclesRoute: typeof AppCirclesRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppMoreRoute: typeof AppMoreRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTimeRoute: typeof AppTimeRoute
  AppWeekRoute: typeof AppWeekRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCirclesRoute: AppCirclesRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppMoreRoute: AppMoreRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTimeRoute: AppTimeRoute,
  AppWeekRoute: AppWeekRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AttachmentsRouteChildren {
  AttachmentsIdRoute: typeof AttachmentsIdRoute
}

const AttachmentsRouteChildren: AttachmentsRouteChildren = {
  AttachmentsIdRoute: AttachmentsIdRoute,
}

const AttachmentsRouteWithChildren = AttachmentsRoute._addFileChildren(
  AttachmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AttachmentsRoute: AttachmentsRouteWithChildren,
  LiveRoute: LiveRoute,
  SignInRoute: SignInRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  DevSeedRoute: DevSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
